### ISSUE TITLE
Memory leak and high CPU usage

### ISSUE THREAD

**Issue by whatakey** [sbechet/xmrsplayer#1]
Hi, thank you for this nice crate :)

When I tried the included example in `src/bin/player.rs` I was surprised to see big memory consumption and CPU usage!

![Untitled](https://user-images.githubusercontent.com/126112966/234662499-0f1963f3-34e3-47fe-abe6-67a32ca27171.png)

**Comment by sbechet** [comment]
Hi whatakey,

Thank you.

I know the problem and I need to do something, but I don't have time to make the change now.
The bug comes from how rodio works (another thread): `sink.append()` must be outside the loop.

I'll add a `Source` rodio trait whenever possible to simplify the example. I also want to leave `Module` editable in the root thread, so probably add some `Arc<Mutex<>>`.

If you want, send me a pull request.

Have a nice day.

**Comment by whatakey** [comment]
Thank you, I hope you can fix it as soon as you can, no Idea how to implement myself (newbie)

**Comment by sbechet** [comment]
If Ok for you, you can close the bug.

**Comment by whatakey** [comment]
Hi @sbechet thank for fixing this it works but with a caveat :)

The memory leak stopped but I had to add this inside the infinite loop because one of the CPU cores was always working 100%

```Rust
    loop{
        std::thread::sleep(std::time::Duration::from_millis(1000));
    };
```

I didn't get that 100% load In the new included example because there's a check of stdout for key presses which gives the CPU a bit of a break from the infinite loop:
```Rust
loop {
    if let Ok(character) = stdout.read_key() {
        match character {
            Key::Enter => {
                println!("Example");
            }
            Key::Escape => {
                println!("Have a nice day!");
                sink.stop();
                return;
            }
            _ => {}
        }
    }
}
```

I'm closing this issue but IMO that infinite needs to be handled better, Thank you again.
